### ISSUE TITLE
Add descriptions to the library management page

### ISSUE THREAD

**Issue by CalebJ2** [wwu-cs/Submitty#103]
Replace the latin text with instructions/description.

Add instructions to each tab showing things like the folder structure things should be in and what file path means.

**Comment by mwilde1998** [comment]
Updated descriptions under the "Upload" and "Git" tab have been added, most notably a mock file structure for how gradeables should be organized in an uploaded .zip file. The file path tab has since been axed, so no descriptions have been updated there.

HomeworkView.php still has some latin text, but it sounds like this whole page may eventually get removed. Currently, the page is a placeholder anyways, so there's no point in updating the descriptions.
